[package]
name = "fractalbot"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
argh = "0.1.12"
cgmath = "0.18.0"
futures-retry = "0.6.0"
image = { version = "0.24.7", default-features = false, features = ["png"] }
megalodon = { version = "0.11.6", default-features = false, features = ["native-tls"] }
num-complex = { version = "0.4.4", features = ["rand"] }
rand = "0.8.5"
rand_distr = "0.4.3"
tokio = { version = "1.34.0", default-features = false }
rayon = "1.8.0"
