name: Post to Mastodon

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - name: Set up Nix cache
        uses: cachix/cachix-action@v16
        with:
          name: '${{ secrets.CACHIX_NAME }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run fractalbot with Nix
        run: nix run . -- post --status-visibility public
        env:
          MASTODON_INSTANCE_URL: ${{ secrets.MASTODON_INSTANCE_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
