name: Post to Mastodon

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run fractalbot with Nix
        run: nix run . -- post --status-visibility public
        env:
          MASTODON_INSTANCE_URL: ${{ secrets.MASTODON_INSTANCE_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
